home:
    path: /
    controller: App\Controller\HomeController::index

don:
    path: /don
    controller: App\Controller\HomeController::don

mensuel:
    path: /mensuel
    controller: App\Controller\HomeController::mensuel